# Generated by Django 3.2.4 on 2021-08-23 09:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_article_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='LikeRecord',
        ),
    ]
